env:
  browser: true
  es6: false
  node: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 5
parser: babel-eslint
rules: {
  require-jsdoc: off,
  max-len: 0,
  prefer-rest-params: 0,
  prefer-spread: 0,
  no-var: 0,
  guard-for-in: 0,
}
